<div class="sort-by">
    <label><?php echo $this->__('Sort By') ?></label>
    <select onchange="setLocation(this.value)">
        <?php foreach ($this->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?php echo $this->getOrderUrl($_key,
                'asc') ?>"<?php if ($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                <?php echo $this->__($_order) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($this->getCurrentDirection() === 'desc'): ?>
        <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>"
           title="<?php echo $this->__('Set Ascending Direction') ?>">Set Ascending Direction</a>
    <?php else: ?>
        <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>"
           title="<?php echo $this->__('Set Descending Direction') ?>">Set Descending Direction</a>
    <?php endif; ?>
</div>