<?php
    extract(Mage::registry('viewed_product'));
    $lifetime = Mage::helper('viewedproducts/lifetime')->getLifetime();
?>
<script>
    var viewedList = localStorage.getItem("viewed_products");
    if (!viewedList || viewedList === "[]") {
        viewedList = {};
    } else {
        viewedList = JSON.parse(viewedList);
    }
        if(viewedList.<?= $sku ?>) {
            delete viewedList.<?= $sku ?>;
        }
        viewedList.<?= $sku ?> = <?= $productInfo ?>;
        renderStorage(viewedList, <?= $lifetime ?>);
        alert('in GETHERER');
</script>