<?php
    extract(Mage::registry('viewed_commodity'));
    $lifetime = Mage::helper('viewedcommodities')->getLifetime();
?>
<script>
    var viewedList = localStorage.getItem("viewed_commodities");
    if (!viewedList || viewedList === "[]") {
        viewedList = {};
    } else {
        viewedList = JSON.parse(viewedList);
    }
        viewedList.<?= $sku ?> = <?= $productInfo ?>;
        renderStorage(viewedList, <?= $lifetime ?>);
</script>